name: Build Tunarr App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tunarr/**'
      - '.github/workflows/build.yaml'

jobs:
  build-app:
    name: Build App
    uses: ./.github/workflows/build-app.yaml
    with:
      app: tunarr
      publish: true
